### ISSUE TITLE
RAM section overflow when using gcc 10

### ISSUE THREAD

**Issue by marian-m12l** [marian-m12l/game-and-watch-smw#4]

**Comment by PrimoAngelo** [comment]
Same:
/usr/share/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: build/gw_smw.elf section `.bss' will not fit in region `RAM'
/usr/share/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: region `RAM' overflowed by 5904 bytes
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:401: build/gw_smw.elf] Errore 1
make[1]: uscita dalla directory «/home/PC/game-and-watch/game-and-watch-smw»
make: *** [Makefile:461: flash] Errore 2
